services:
  my-portfolio-website:
    container_name: "my-portfolio-website"
    image: portfolio-website:latest
    ports:
      - 2387:2387
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - swag_reverse_proxy

  redis_storage_backend:
    container_name: redis_storage_backend
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - swag_reverse_proxy

networks:
  swag_reverse_proxy:
    external: true
